package api

import "reflect"

func YaegiSymbols() map[string]reflect.Value {
	return map[string]reflect.Value{
		"Package":           reflect.ValueOf((*Package)(nil)),
		"Target":            reflect.ValueOf((*Target)(nil)),
		"Option":            reflect.ValueOf((*Option)(nil)),
		"BuildContext":      reflect.ValueOf((*BuildContext)(nil)),
		"ConfigContext":     reflect.ValueOf((*ConfigContext)(nil)),
		"CleanContext":      reflect.ValueOf((*CleanContext)(nil)),
		"InstallContext":    reflect.ValueOf((*InstallContext)(nil)),
		"ConfigAccessor":    reflect.ValueOf((*ConfigAccessor)(nil)),
		"TargetRegistry":    reflect.ValueOf((*TargetRegistry)(nil)),
		"InstallItemHolder": reflect.ValueOf((*InstallItemHolder)(nil)),
		"InstallItem":       reflect.ValueOf((*InstallItem)(nil)),
		"KConfigEntry":      reflect.ValueOf((*KConfigEntry)(nil)),
		"Version":           reflect.ValueOf((*Version)(nil)),
		"Constraint":        reflect.ValueOf((*Constraint)(nil)),
		"RequireContext":    reflect.ValueOf((*RequireContext)(nil)),
		"Requires":          reflect.ValueOf((*Requires)(nil)),
		"RequireInfo":       reflect.ValueOf((*RequireInfo)(nil)),
		"PkgDirs":           reflect.ValueOf((*PkgDirs)(nil)),
		"PackageMeta":       reflect.ValueOf((*PackageMeta)(nil)),
		"InstalledPackage":  reflect.ValueOf((*InstalledPackage)(nil)),
		"PostLinkStep":      reflect.ValueOf((*PostLinkStep)(nil)),
		"GenRule":           reflect.ValueOf((*GenRule)(nil)),

		"TargetKind":   reflect.ValueOf((*TargetKind)(nil)),
		"OptionType":   reflect.ValueOf((*OptionType)(nil)),
		"SourceOrigin": reflect.ValueOf((*SourceOrigin)(nil)),
		"GenRuleKind":  reflect.ValueOf((*GenRuleKind)(nil)),

		"ConfigFunc":        reflect.ValueOf((*ConfigFunc)(nil)),
		"BuildFunc":         reflect.ValueOf((*BuildFunc)(nil)),
		"InstallFunc":       reflect.ValueOf((*InstallFunc)(nil)),
		"CleanFunc":         reflect.ValueOf((*CleanFunc)(nil)),
		"PackageFunc":       reflect.ValueOf((*PackageFunc)(nil)),
		"RequireFunc":       reflect.ValueOf((*RequireFunc)(nil)),
		"CopyFilter":        reflect.ValueOf((*CopyFilter)(nil)),
		"InstallFilterFunc": reflect.ValueOf((*InstallFilterFunc)(nil)),

		"NewPackage":                  reflect.ValueOf(NewPackage),
		"NewBuildContext":             reflect.ValueOf(NewBuildContext),
		"NewConfigContext":            reflect.ValueOf(NewConfigContext),
		"NewConfigContextWithPackage": reflect.ValueOf(NewConfigContextWithPackage),
		"NewCleanContext":             reflect.ValueOf(NewCleanContext),
		"NewInstallContext":           reflect.ValueOf(NewInstallContext),
		"NewConfigAccessor":           reflect.ValueOf(NewConfigAccessor),
		"NewTargetRegistry":           reflect.ValueOf(NewTargetRegistry),
		"NewInstalledPackage":         reflect.ValueOf(NewInstalledPackage),
		"NewRequireContextForConfig":  reflect.ValueOf(NewRequireContextForConfig),
		"ParseVersion":                reflect.ValueOf(ParseVersion),
		"ParseConstraint":             reflect.ValueOf(ParseConstraint),
		"MatchVersion":                reflect.ValueOf(MatchVersion),
		"MatchPatterns":               reflect.ValueOf(MatchPatterns),
		"MergeGlobalOptions":          reflect.ValueOf(MergeGlobalOptions),
		"MergeImportedOptions":        reflect.ValueOf(MergeImportedOptions),
		"CopyDir":                     reflect.ValueOf(CopyDir),
		"CopyDirIfExists":             reflect.ValueOf(CopyDirIfExists),
		"CopyDirWithFilter":           reflect.ValueOf(CopyDirWithFilter),
		"CopyFile":                    reflect.ValueOf(CopyFile),
		"GetModeFlags":                reflect.ValueOf(GetModeFlags),
		"ConfigToDefines":             reflect.ValueOf(ConfigToDefines),
		"ConfigToHeader":              reflect.ValueOf(ConfigToHeader),
		"WriteConfigHeader":           reflect.ValueOf(WriteConfigHeader),
		"ApplyKConfigPatches":         reflect.ValueOf(ApplyKConfigPatches),
		"CheckCycle":                  reflect.ValueOf(CheckCycle),
		"ResolveSubPackageName":       reflect.ValueOf(ResolveSubPackageName),
		"SplitPackageRef":             reflect.ValueOf(SplitPackageRef),
		"YaegiSymbols":                reflect.ValueOf(YaegiSymbols),

		"TargetBinary":        reflect.ValueOf(TargetBinary),
		"TargetStatic":        reflect.ValueOf(TargetStatic),
		"TargetShared":        reflect.ValueOf(TargetShared),
		"TargetObject":        reflect.ValueOf(TargetObject),
		"TargetVoid":          reflect.ValueOf(TargetVoid),
		"OptionBool":          reflect.ValueOf(OptionBool),
		"OptionString":        reflect.ValueOf(OptionString),
		"OptionInt":           reflect.ValueOf(OptionInt),
		"OptionChoice":        reflect.ValueOf(OptionChoice),
		"SourceLocal":         reflect.ValueOf(SourceLocal),
		"SourceRemote":        reflect.ValueOf(SourceRemote),
		"ModeOptionName":      reflect.ValueOf(ModeOptionName),
		"ToolchainOptionName": reflect.ValueOf(ToolchainOptionName),
		"ModeDebug":           reflect.ValueOf(ModeDebug),
		"ModeRelease":         reflect.ValueOf(ModeRelease),
		"GenRuleBinHeader":    reflect.ValueOf(GenRuleBinHeader),

		"BuiltInGlobalOptions": reflect.ValueOf(&BuiltInGlobalOptions).Elem(),
	}
}
