package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/spock2300/vmake/pkg/version"
)

var (
	initEditorLocal  string
	initEditorRemove bool
)

func newInitEditorCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init-editor",
		Short: "Generate editor support files for build.go (go.mod for gopls)",
		Long: `Writes a scratch go.mod at the project root so build.go files type-check,
autocomplete and rename in gopls-powered editors (VS Code Go, Neovim, GoLand).

The go.mod declares module vmake-script and requires github.com/spock2300/vmake.
build.go files are still interpreted by vmake at runtime; this file only enables
editor tooling and is safe to commit.

Use --local <path> to point the requirement at a local vmake checkout via a
replace directive (useful when developing vmake itself).`,
		Run: runInitEditor,
	}
	cmd.Flags().StringVar(&initEditorLocal, "local", "", "path to a local vmake source tree (adds a replace directive)")
	cmd.Flags().BoolVar(&initEditorRemove, "remove", false, "remove the generated go.mod")
	return cmd
}

func runInitEditor(cmd *cobra.Command, args []string) {
	root := findProjectDir()
	goModPath := filepath.Join(root, "go.mod")

	if initEditorRemove {
		data, err := os.ReadFile(goModPath)
		if err != nil {
			fatalMsg("read %s: %v", goModPath, err)
		}
		if !isGeneratedGoMod(string(data)) {
			fatalMsg("%s was not generated by vmake init-editor; refusing to remove", goModPath)
		}
		if err := os.Remove(goModPath); err != nil {
			fatalMsg("remove %s: %v", goModPath, err)
		}
		fmt.Println("Removed", goModPath)
		return
	}

	if data, err := os.ReadFile(goModPath); err == nil {
		if !isGeneratedGoMod(string(data)) {
			fatalMsg("%s already exists and was not generated by vmake init-editor", goModPath)
		}
	}

	v := version.Version
	if v == "" || v == "dev" {
		v = "v0.0.0"
	}
	content := fmt.Sprintf(`// Generated by vmake init-editor — editor tooling only, not used by builds.
module vmake-script

go 1.26

require github.com/spock2300/vmake %s
`, v)
	if initEditorLocal != "" {
		abs, err := filepath.Abs(initEditorLocal)
		if err != nil {
			fatalMsg("resolve --local path: %v", err)
		}
		content += fmt.Sprintf("\nreplace github.com/spock2300/vmake => %s\n", abs)
	}

	if err := os.WriteFile(goModPath, []byte(content), 0644); err != nil {
		fatalMsg("write %s: %v", goModPath, err)
	}

	fmt.Println("Wrote", goModPath)
	fmt.Println("Run 'go mod tidy' once to resolve the vmake module, then open the project in your editor.")
	fmt.Println("Note: build.go files are entry points for vmake, not standalone Go programs;")
	fmt.Println("'go build ./...' of them is not expected to succeed — gopls only type-checks.")
}

func isGeneratedGoMod(content string) bool {
	return strings.Contains(content, "Generated by vmake init-editor")
}
