package main

import (
	"fmt"
	"os"
	"path/filepath"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"gitee.com/spock2300/vmake/internal/jsonio"
	"gitee.com/spock2300/vmake/pkg/api"
	"gitee.com/spock2300/vmake/pkg/repo"
)

var manifestCmd = &cobra.Command{
	Use:   "manifest",
	Short: "Inspect and restore install manifests",
	Long:  `Manage install manifests generated by 'vmake build --install'.`,
}

var manifestShowCmd = &cobra.Command{
	Use:   "show <path>",
	Short: "Show manifest contents",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		var mf installManifest
		fatalErr(jsonio.Load(args[0], &mf))

		fmt.Printf("VMake:     %s\n", mf.VMake)
		fmt.Printf("Toolchain: %s\n", mf.Toolchain)
		fmt.Printf("Mode:      %s\n", mf.Mode)
		fmt.Printf("Generated: %s\n", mf.Generated)
		fmt.Println()

		if len(mf.Packages) == 0 {
			fmt.Println("No packages recorded.")
			return
		}

		w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
		fmt.Fprintln(w, "NAME\tVERSION\tSOURCE\tREF\tURL/PATH")
		for _, p := range mf.Packages {
			ref := p.Ref
			urlOrPath := p.Path
			if urlOrPath == "" {
				urlOrPath = p.URL
			}
			if ref != "" && len(ref) > 12 {
				ref = ref[:12] + "..."
			}
			fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", p.Name, p.Version, p.Source, ref, urlOrPath)
		}
		w.Flush()
	},
}

var manifestCheckoutCmd = &cobra.Command{
	Use:   "checkout <path> [name]",
	Short: "Checkout packages to recorded versions",
	Long:  `Restore all (or a specific) package source to the version recorded in the manifest.`,
	Args:  cobra.RangeArgs(1, 2),
	Run: func(cmd *cobra.Command, args []string) {
		manifestPath := args[0]
		filterName := ""
		if len(args) > 1 {
			filterName = args[1]
		}

		var mf installManifest
		fatalErr(jsonio.Load(manifestPath, &mf))

		cwd, err := os.Getwd()
		fatalErr(err)

		sourceMgr := repo.NewSourceManager(getCacheDir())

		found := false
		for _, entry := range mf.Packages {
			if filterName != "" && entry.Name != filterName {
				continue
			}
			found = true

			switch entry.Source {
			case "local":
				checkoutLocal(cwd, entry)
			case "prefix", "index":
				checkoutRemote(sourceMgr, entry)
			default:
				fmt.Printf("  SKIP %s (unknown source: %s)\n", entry.Name, entry.Source)
			}
		}

		if filterName != "" && !found {
			fatalMsg("Package '%s' not found in manifest", filterName)
		}
	},
}

func checkoutLocal(cwd string, entry installManifestEntry) {
	if entry.Ref == "" || entry.Ref == "unknown" {
		fmt.Printf("  SKIP %s (no ref recorded)\n", entry.Name)
		return
	}

	sourceDir := filepath.Join(cwd, entry.Path)
	if _, err := os.Stat(sourceDir); err != nil {
		fmt.Printf("  SKIP %s (path not found: %s)\n", entry.Name, entry.Path)
		return
	}

	if err := repo.Checkout(sourceDir, entry.Ref); err != nil {
		fmt.Printf("  FAIL %s (checkout %s: %v)\n", entry.Name, entry.Ref[:12]+"...", err)
	} else {
		fmt.Printf("  OK   %s -> %s\n", entry.Name, entry.Ref[:12]+"...")
	}
}

func checkoutRemote(sourceMgr *repo.SourceManager, entry installManifestEntry) {
	if entry.Ref == "" {
		fmt.Printf("  SKIP %s (no ref recorded)\n", entry.Name)
		return
	}

	repoName, pkgName, ok := api.SplitPackageRef(entry.Name)
	if !ok {
		fmt.Printf("  SKIP %s (invalid package reference)\n", entry.Name)
		return
	}

	pkg := newPkgRef(repoName, pkgName)
	if entry.URL != "" {
		pkg.SetGit(entry.URL)
	}

	if _, err := sourceMgr.EnsureSource(pkg, entry.Ref); err != nil {
		fmt.Printf("  FAIL %s (%v)\n", entry.Name, err)
		return
	}

	buildCacheDir := filepath.Join(getPackagesDir(), repoName, pkgName)
	if _, err := os.Stat(buildCacheDir); err == nil {
		os.RemoveAll(buildCacheDir)
		fmt.Printf("  OK   %s -> %s (build cache cleared)\n", entry.Name, entry.Ref)
	} else {
		fmt.Printf("  OK   %s -> %s\n", entry.Name, entry.Ref)
	}
}

func init() {
	manifestCmd.AddCommand(manifestShowCmd)
	manifestCmd.AddCommand(manifestCheckoutCmd)
	RootCmd.AddCommand(manifestCmd)
}
